debug:
  enabled: true
  server:
    enabled: true

application:
  title: High School Story
  useVsync: true
  displayMode: WINDOWED
  resolution:
    width: 1270
    height: 720
  refreshRate: 60

meterCamera:
  viewportWidth: 23
  viewportHeight: 13
